//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTrans.Service.UI.CommonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonService.ICommonService")]
    public interface ICommonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SelectPage", ReplyAction="http://tempuri.org/ICommonService/SelectPageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Enum.TableNames))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SelectPage(out int rowCount, SoftTrans.Service.Entity.Enum.TableNames t, int pageIndex, int pageSize, object where, object[] aopPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Select", ReplyAction="http://tempuri.org/ICommonService/SelectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Enum.TableNames))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string Select(SoftTrans.Service.Entity.Enum.TableNames t, object where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SelectColumns", ReplyAction="http://tempuri.org/ICommonService/SelectColumnsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Enum.TableNames))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SelectColumns(SoftTrans.Service.Entity.Enum.TableNames t, object where, object[] columnsName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Delete", ReplyAction="http://tempuri.org/ICommonService/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Enum.TableNames))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool Delete(SoftTrans.Service.Entity.Enum.TableNames t, object where, object[] aopPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Update", ReplyAction="http://tempuri.org/ICommonService/UpdateResponse")]
        bool Update(SoftTrans.Service.Entity.Enum.TableNames t, string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Insert", ReplyAction="http://tempuri.org/ICommonService/InsertResponse")]
        bool Insert(SoftTrans.Service.Entity.Enum.TableNames t, string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/Fill", ReplyAction="http://tempuri.org/ICommonService/FillResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Enum.TableNames))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string Fill(SoftTrans.Service.Entity.Enum.TableNames t, object where);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonServiceChannel : SoftTrans.Service.UI.CommonService.ICommonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonServiceClient : System.ServiceModel.ClientBase<SoftTrans.Service.UI.CommonService.ICommonService>, SoftTrans.Service.UI.CommonService.ICommonService {
        
        public CommonServiceClient() {
        }
        
        public CommonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SelectPage(out int rowCount, SoftTrans.Service.Entity.Enum.TableNames t, int pageIndex, int pageSize, object where, object[] aopPara) {
            return base.Channel.SelectPage(out rowCount, t, pageIndex, pageSize, where, aopPara);
        }
        
        public string Select(SoftTrans.Service.Entity.Enum.TableNames t, object where) {
            return base.Channel.Select(t, where);
        }
        
        public string SelectColumns(SoftTrans.Service.Entity.Enum.TableNames t, object where, object[] columnsName) {
            return base.Channel.SelectColumns(t, where, columnsName);
        }
        
        public bool Delete(SoftTrans.Service.Entity.Enum.TableNames t, object where, object[] aopPara) {
            return base.Channel.Delete(t, where, aopPara);
        }
        
        public bool Update(SoftTrans.Service.Entity.Enum.TableNames t, string json) {
            return base.Channel.Update(t, json);
        }
        
        public bool Insert(SoftTrans.Service.Entity.Enum.TableNames t, string json) {
            return base.Channel.Insert(t, json);
        }
        
        public string Fill(SoftTrans.Service.Entity.Enum.TableNames t, object where) {
            return base.Channel.Fill(t, where);
        }
    }
}
