//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTrans.Service.UI.BaseFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BaseFileService.IBaseFileService")]
    public interface IBaseFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Insert_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Insert_T_baseBalanceExchange_RateResponse")]
        SoftTrans.Service.Entity.T_baseBalanceExchange_Rate Insert_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Update_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Update_T_baseBalanceExchange_RateResponse")]
        bool Update_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Delete_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Delete_T_baseBalanceExchange_RateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        bool Delete_T_baseBalanceExchange_Rate(object keyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Load_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Load_T_baseBalanceExchange_RateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string Load_T_baseBalanceExchange_Rate(object where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/LoadPage_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/LoadPage_T_baseBalanceExchange_RateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string LoadPage_T_baseBalanceExchange_Rate(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Insert_Hrm_Country", ReplyAction="http://tempuri.org/IBaseFileService/Insert_Hrm_CountryResponse")]
        SoftTrans.Service.Entity.Hrm_Country Insert_Hrm_Country(SoftTrans.Service.Entity.Hrm_Country entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Update_Hrm_Country", ReplyAction="http://tempuri.org/IBaseFileService/Update_Hrm_CountryResponse")]
        bool Update_Hrm_Country(SoftTrans.Service.Entity.Hrm_Country entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Delete_Hrm_Country", ReplyAction="http://tempuri.org/IBaseFileService/Delete_Hrm_CountryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        bool Delete_Hrm_Country(object keyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Load_Hrm_Country", ReplyAction="http://tempuri.org/IBaseFileService/Load_Hrm_CountryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string Load_Hrm_Country(object where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/LoadPage_Hrm_Country", ReplyAction="http://tempuri.org/IBaseFileService/LoadPage_Hrm_CountryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string LoadPage_Hrm_Country(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Insert_Hrm_Province", ReplyAction="http://tempuri.org/IBaseFileService/Insert_Hrm_ProvinceResponse")]
        SoftTrans.Service.Entity.Hrm_Province Insert_Hrm_Province(SoftTrans.Service.Entity.Hrm_Province entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Update_Hrm_Province", ReplyAction="http://tempuri.org/IBaseFileService/Update_Hrm_ProvinceResponse")]
        bool Update_Hrm_Province(SoftTrans.Service.Entity.Hrm_Province entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Delete_Hrm_Province", ReplyAction="http://tempuri.org/IBaseFileService/Delete_Hrm_ProvinceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        bool Delete_Hrm_Province(object keyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Load_Hrm_Province", ReplyAction="http://tempuri.org/IBaseFileService/Load_Hrm_ProvinceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string Load_Hrm_Province(object where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/LoadPage_Hrm_Province", ReplyAction="http://tempuri.org/IBaseFileService/LoadPage_Hrm_ProvinceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string LoadPage_Hrm_Province(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Insert_Hrm_City", ReplyAction="http://tempuri.org/IBaseFileService/Insert_Hrm_CityResponse")]
        SoftTrans.Service.Entity.Hrm_City Insert_Hrm_City(SoftTrans.Service.Entity.Hrm_City entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Update_Hrm_City", ReplyAction="http://tempuri.org/IBaseFileService/Update_Hrm_CityResponse")]
        bool Update_Hrm_City(SoftTrans.Service.Entity.Hrm_City entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Delete_Hrm_City", ReplyAction="http://tempuri.org/IBaseFileService/Delete_Hrm_CityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        bool Delete_Hrm_City(object keyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Load_Hrm_City", ReplyAction="http://tempuri.org/IBaseFileService/Load_Hrm_CityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string Load_Hrm_City(object where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/LoadPage_Hrm_City", ReplyAction="http://tempuri.org/IBaseFileService/LoadPage_Hrm_CityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Country))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_Province))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.Hrm_City))]
        string LoadPage_Hrm_City(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaseFileServiceChannel : SoftTrans.Service.UI.BaseFileService.IBaseFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaseFileServiceClient : System.ServiceModel.ClientBase<SoftTrans.Service.UI.BaseFileService.IBaseFileService>, SoftTrans.Service.UI.BaseFileService.IBaseFileService {
        
        public BaseFileServiceClient() {
        }
        
        public BaseFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoftTrans.Service.Entity.T_baseBalanceExchange_Rate Insert_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity) {
            return base.Channel.Insert_T_baseBalanceExchange_Rate(entity);
        }
        
        public bool Update_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity) {
            return base.Channel.Update_T_baseBalanceExchange_Rate(entity);
        }
        
        public bool Delete_T_baseBalanceExchange_Rate(object keyId) {
            return base.Channel.Delete_T_baseBalanceExchange_Rate(keyId);
        }
        
        public string Load_T_baseBalanceExchange_Rate(object where) {
            return base.Channel.Load_T_baseBalanceExchange_Rate(where);
        }
        
        public string LoadPage_T_baseBalanceExchange_Rate(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara) {
            return base.Channel.LoadPage_T_baseBalanceExchange_Rate(out rowCount, pageIndex, pageSize, where, aopPara);
        }
        
        public SoftTrans.Service.Entity.Hrm_Country Insert_Hrm_Country(SoftTrans.Service.Entity.Hrm_Country entity) {
            return base.Channel.Insert_Hrm_Country(entity);
        }
        
        public bool Update_Hrm_Country(SoftTrans.Service.Entity.Hrm_Country entity) {
            return base.Channel.Update_Hrm_Country(entity);
        }
        
        public bool Delete_Hrm_Country(object keyId) {
            return base.Channel.Delete_Hrm_Country(keyId);
        }
        
        public string Load_Hrm_Country(object where) {
            return base.Channel.Load_Hrm_Country(where);
        }
        
        public string LoadPage_Hrm_Country(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara) {
            return base.Channel.LoadPage_Hrm_Country(out rowCount, pageIndex, pageSize, where, aopPara);
        }
        
        public SoftTrans.Service.Entity.Hrm_Province Insert_Hrm_Province(SoftTrans.Service.Entity.Hrm_Province entity) {
            return base.Channel.Insert_Hrm_Province(entity);
        }
        
        public bool Update_Hrm_Province(SoftTrans.Service.Entity.Hrm_Province entity) {
            return base.Channel.Update_Hrm_Province(entity);
        }
        
        public bool Delete_Hrm_Province(object keyId) {
            return base.Channel.Delete_Hrm_Province(keyId);
        }
        
        public string Load_Hrm_Province(object where) {
            return base.Channel.Load_Hrm_Province(where);
        }
        
        public string LoadPage_Hrm_Province(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara) {
            return base.Channel.LoadPage_Hrm_Province(out rowCount, pageIndex, pageSize, where, aopPara);
        }
        
        public SoftTrans.Service.Entity.Hrm_City Insert_Hrm_City(SoftTrans.Service.Entity.Hrm_City entity) {
            return base.Channel.Insert_Hrm_City(entity);
        }
        
        public bool Update_Hrm_City(SoftTrans.Service.Entity.Hrm_City entity) {
            return base.Channel.Update_Hrm_City(entity);
        }
        
        public bool Delete_Hrm_City(object keyId) {
            return base.Channel.Delete_Hrm_City(keyId);
        }
        
        public string Load_Hrm_City(object where) {
            return base.Channel.Load_Hrm_City(where);
        }
        
        public string LoadPage_Hrm_City(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara) {
            return base.Channel.LoadPage_Hrm_City(out rowCount, pageIndex, pageSize, where, aopPara);
        }
    }
}
