//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTrans.Service.UI.BaseFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BaseFileService.IBaseFileService")]
    public interface IBaseFileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Insert_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Insert_T_baseBalanceExchange_RateResponse")]
        SoftTrans.Service.Entity.T_baseBalanceExchange_Rate Insert_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Update_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Update_T_baseBalanceExchange_RateResponse")]
        bool Update_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Delete_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Delete_T_baseBalanceExchange_RateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        bool Delete_T_baseBalanceExchange_Rate(object keyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/Load_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/Load_T_baseBalanceExchange_RateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        string Load_T_baseBalanceExchange_Rate(object where);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBaseFileService/LoadPage_T_baseBalanceExchange_Rate", ReplyAction="http://tempuri.org/IBaseFileService/LoadPage_T_baseBalanceExchange_RateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate))]
        string LoadPage_T_baseBalanceExchange_Rate(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBaseFileServiceChannel : SoftTrans.Service.UI.BaseFileService.IBaseFileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaseFileServiceClient : System.ServiceModel.ClientBase<SoftTrans.Service.UI.BaseFileService.IBaseFileService>, SoftTrans.Service.UI.BaseFileService.IBaseFileService {
        
        public BaseFileServiceClient() {
        }
        
        public BaseFileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseFileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseFileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseFileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoftTrans.Service.Entity.T_baseBalanceExchange_Rate Insert_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity) {
            return base.Channel.Insert_T_baseBalanceExchange_Rate(entity);
        }
        
        public bool Update_T_baseBalanceExchange_Rate(SoftTrans.Service.Entity.T_baseBalanceExchange_Rate entity) {
            return base.Channel.Update_T_baseBalanceExchange_Rate(entity);
        }
        
        public bool Delete_T_baseBalanceExchange_Rate(object keyId) {
            return base.Channel.Delete_T_baseBalanceExchange_Rate(keyId);
        }
        
        public string Load_T_baseBalanceExchange_Rate(object where) {
            return base.Channel.Load_T_baseBalanceExchange_Rate(where);
        }
        
        public string LoadPage_T_baseBalanceExchange_Rate(out int rowCount, int pageIndex, int pageSize, object where, object[] aopPara) {
            return base.Channel.LoadPage_T_baseBalanceExchange_Rate(out rowCount, pageIndex, pageSize, where, aopPara);
        }
    }
}
